"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EncryptedERC__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var EncryptedERC__factory_1 = require("./EncryptedERC__factory");
Object.defineProperty(exports, "EncryptedERC__factory", { enumerable: true, get: function () { return EncryptedERC__factory_1.EncryptedERC__factory; } });
